version: '3'

services:
  api-proxy-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:8081
      - 9229:9229
    environment:
      - NODE_ENV=development
    command: npm run start
